// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      // case TargetPlatform.macOS:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for macos - '
      //     'you can reconfigure this by running the FlutterFire CLI again.',
      // );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB27blw-vPKf9sRPPn4ulLn8XgfZJHdj24',
    appId: '1:268373554625:web:2cd3242b75cfff3d31ab40',
    messagingSenderId: '268373554625',
    projectId: 'shuffler-f1e36',
    authDomain: 'shuffler-f1e36.firebaseapp.com',
    storageBucket: 'shuffler-f1e36.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB27blw-vPKf9sRPPn4ulLn8XgfZJHdj24',
    appId:
        '1:268373554625:android:8eac72f1c08b725531ab401:268373554625:android:8eac72f1c08b725531ab40',
    messagingSenderId: '268373554625',
    projectId: 'shuffler-f1e36',
    storageBucket: 'shuffler-f1e36.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyDyG9BWS7SmLNwIzYNC27tKPZMseQHjWhQ',
  //   appId: '1:1023967397536:ios:186406ec1f4a7de7b5ebc5',
  //   messagingSenderId: '1023967397536',
  //   projectId: 'sliding-scene',
  //   storageBucket: 'shuffler-f1e36.appspot.com',
  //   iosClientId:
  //       '1023967397536-cdprd8vhku8pgnsm0c41v87u2fci3f71.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.slidingscene',
  // );
}
